volumes:
  data:

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 55002:27017
    volumes:
      - data:/data/db

